debug = false
secret = "__MTG_SECRET__"
bind-to = "0.0.0.0:__PORT__"
api-bind-to = "127.0.0.1:9090"

[network]
dns = "https://__DNS__"

[throttle]
max-connections = 500
check-interval = "5s"

[stats.prometheus]
enabled = __PROM_ENABLED__
bind-to = "127.0.0.1:3129"
http-path = "/"
metric-prefix = "mtg"
