#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing systemd service..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd
ynh_config_remove_logrotate

#=================================================
# REMOVE WEB CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx and php-fpm configuration..."

ynh_config_remove_nginx
ynh_config_remove_phpfpm

#=================================================
# REMOVE USER HOOKS
# Note: system user, install_dir, apt packages, firewall ports and logs
# are automatically removed by YunoHost via [resources]
#=================================================
ynh_script_progression "Removing user hooks..."

mtg_remove_hooks

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
