#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing systemd service..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_remove_nginx_config

#=================================================
# REMOVE CONFIGURATION FILES
# Note: system user, install_dir, apt packages, and firewall ports
# are automatically removed by YunoHost via [resources]
#=================================================
ynh_script_progression "Removing configuration files..."

ynh_safe_rm "$install_dir/conf"
ynh_safe_rm "$install_dir/index.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
