#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"
chmod 700 "$install_dir/conf"
chmod 600 "$install_dir/conf/mtg.toml" "$install_dir/conf/secrets.toml"

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_config_add_phpfpm
ynh_config_add_nginx
ynh_config_add_systemd
ynh_config_add_logrotate "/var/log/$app/$app.log"

mtg_add_hooks

yunohost service add "$app" \
    --description "MTProto proxy for Telegram (mtg-multi)" \
    --needs_exposed_ports "$port" \
    --log="/var/log/$app/$app.log"

#=================================================
# RELOAD THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --action=enable
ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
